# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-08-11 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name', max_length=4096)),
                ('records', models.IntegerField(help_text='records or bands')),
                ('modified', models.DateTimeField(help_text='time of last modification')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='Attr_type',
            fields=[
                ('attr_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name', max_length=4096)),
            ],
            options={
                'db_table': 'attr_type',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name of attribute', max_length=4096)),
                ('asset', models.ForeignKey(db_column='asset', help_text='asset', on_delete=django.db.models.deletion.CASCADE, to='gis_asset_app.Asset')),
                ('attr_type', models.ForeignKey(db_column='attr_type', on_delete=django.db.models.deletion.CASCADE, to='gis_asset_app.Attr_type')),
            ],
            options={
                'db_table': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='Bounds',
            fields=[
                ('bounds', models.AutoField(primary_key=True, serialize=False)),
                ('srid', models.IntegerField(blank=True, help_text='Spatial Reference ID', null=True)),
                ('minx', models.FloatField(help_text='minx')),
                ('maxx', models.FloatField(help_text='maxx')),
                ('miny', models.FloatField(help_text='miny')),
                ('maxy', models.FloatField(help_text='maxy')),
                ('cellsx', models.IntegerField(blank=True, help_text='Raster cells in x axis', null=True)),
                ('cellsy', models.IntegerField(blank=True, help_text='Raster cells in y axis', null=True)),
                ('sizex', models.FloatField(blank=True, help_text='Raster cell x size', null=True)),
                ('sizey', models.FloatField(blank=True, help_text='Raster cell y size', null=True)),
                ('asset', models.ForeignKey(db_column='asset', help_text='asset', on_delete=django.db.models.deletion.CASCADE, to='gis_asset_app.Asset')),
            ],
            options={
                'db_table': 'bounds',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('drive', models.AutoField(primary_key=True, serialize=False)),
                ('letter', models.CharField(help_text='drive letter', max_length=4096)),
                ('machine', models.CharField(help_text='mount point', max_length=4096)),
                ('share', models.CharField(help_text='share name', max_length=4096)),
                ('last_scanned', models.DateField(blank=True, help_text='last scan date', null=True)),
                ('user', models.CharField(blank=True, help_text='password:user', max_length=4096)),
                ('ip', models.CharField(blank=True, help_text='IP to try if lookup fails', max_length=4096)),
            ],
            options={
                'db_table': 'drive',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('format', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name', max_length=4096)),
            ],
            options={
                'db_table': 'format',
            },
        ),
        migrations.CreateModel(
            name='Geom_type',
            fields=[
                ('geom_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name', max_length=4096)),
            ],
            options={
                'db_table': 'geom_type',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('path', models.AutoField(primary_key=True, serialize=False)),
                ('path_txt', models.CharField(help_text='path', max_length=4096)),
                ('asset', models.ForeignKey(db_column='asset', help_text='asset', on_delete=django.db.models.deletion.CASCADE, to='gis_asset_app.Asset')),
            ],
            options={
                'db_table': 'path',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='format',
            field=models.ManyToManyField(to='gis_asset_app.Format'),
        ),
        migrations.AddField(
            model_name='asset',
            name='geom_type',
            field=models.ManyToManyField(to='gis_asset_app.Geom_type'),
        ),
    ]
